-- Treesitter indent is now enabled globally via the nvim-treesitter config.
-- cindent was previously overridden here because it misindents after Rust
-- structs (no trailing ;) since it's a C indenter.
